openapi: 3.0.0
info:
  title: Social Network API
  description: API for social network posts
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local development server
paths:
  /posts:
    get:
      summary: Get paginated list of posts
      description: Returns a paginated list of posts with optional filtering
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number
        - in: query
          name: per_page
          schema:
            type: integer
            default: 10
          description: Number of items per page
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
                  total:
                    type: integer
                  page:
                    type: integer
                  per_page:
                    type: integer
        '401':
          description: Unauthorized - Authentication token is missing or invalid
        '500':
          description: Internal server error
    post:
      summary: Create a new post
      description: Create a new post with the provided information
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - description
              properties:
                title:
                  type: string
                description:
                  type: string
                is_private:
                  type: boolean
                  default: false
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Post created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Bad request - Missing required fields
        '401':
          description: Unauthorized - Authentication token is missing or invalid
        '500':
          description: Internal server error
  
  /posts/{post_id}:
    get:
      summary: Get a post by ID
      description: Returns a single post by its ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: post_id
          required: true
          schema:
            type: integer
          description: ID of the post to retrieve
      responses:
        '200':
          description: A single post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '401':
          description: Unauthorized - Authentication token is missing or invalid
        '403':
          description: Forbidden - User does not have permission to view this post
        '404':
          description: Post not found
        '500':
          description: Internal server error
    
    put:
      summary: Update a post
      description: Update a post with the provided information
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: post_id
          required: true
          schema:
            type: integer
          description: ID of the post to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                is_private:
                  type: boolean
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Post updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '401':
          description: Unauthorized - Authentication token is missing or invalid
        '403':
          description: Forbidden - User does not have permission to update this post
        '404':
          description: Post not found
        '500':
          description: Internal server error
    
    delete:
      summary: Delete a post
      description: Delete a post by its ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: post_id
          required: true
          schema:
            type: integer
          description: ID of the post to delete
      responses:
        '200':
          description: Post deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '401':
          description: Unauthorized - Authentication token is missing or invalid
        '403':
          description: Forbidden - User does not have permission to delete this post
        '404':
          description: Post not found
        '500':
          description: Internal server
