FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest pytest-cov pytest-mock

RUN mkdir -p proto

COPY proto/ ./proto/

COPY *.py .
COPY tests/ ./tests/

RUN python -m grpc_tools.protoc -I./proto --python_out=. --grpc_python_out=. ./proto/stats_service.proto

CMD ["pytest", "tests/", "-v", "--cov=."]
